In [ ]:
pip install tensorflow


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
a=tf.constant(5)
print(a)

v=tf.constant([1,2,3,4])
print(v)

m = tf.constant([[1,2], [3,4]])
print(m)

t3=tf.constant([[[1,2],
                [3,4]],
                [[5,6],
                [7,8]]])
print(t3)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [ ]:
a = tf.constant([10, 20, 30])
b = tf.constant([50, 60, 70])
print(a+b)

tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)


In [ ]:
a = tf.constant([10, 20, 20])
print(a.dtype, a.shape, tf.rank(a))

<dtype: 'int32'> (3,) tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
import numpy as np
np_array = np.array([[1,2,3], [4,5,6]])

tensor = tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
